# 系统设置
server:
  port: 8888

spring:
  # 数据源配置
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/transport_security?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
