# 系统设置
server:
  port: 8889

spring:
  # 数据源配置
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/db_transport_security?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 106.52.60.176
    port: 6379
    password: brysj$@!HHRHL
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8

auth:
  white-uris:
    - '/auth/login'
    - '/auth/register'

# Socket配置
socket:
  # 监听端口 8888
  port: 8888
  # 线程池 - 保持线程数 20
  pool-keep: 5
  # 线程池 - 核心线程数 10
  pool-core: 2
  # 线程池 - 最大线程数 20
  pool-max: 10
  # 线程队列容量 10
  pool-queue-init: 2
